import { Type } from 'class-transformer';
import {
  ArrayMaxSize,
  IsArray,
  IsIn,
  IsInt,
  IsOptional,
  IsString,
  IsUUID,
  MaxLength,
  Min,
  Max,
  MinLength,
  ValidateNested,
} from 'class-validator';

/**
 * One prior turn, as the client already has it on screen.
 *
 * Sent by the client rather than rebuilt from `assistant_exchanges`, so the
 * request path never reads that table. Length is capped here as well as in the
 * service: a caller who posts a megabyte of history is billing the company for
 * input tokens, and the guard belongs at the edge.
 */
export class ChatTurnDto {
  @IsIn(['user', 'assistant'])
  role!: 'user' | 'assistant';

  @IsString()
  @MaxLength(8000)
  content!: string;
}

export class ChatDto {
  /** Generated by the client when the panel opens. Groups an exchange log. */
  @IsUUID()
  conversation_id!: string;

  @IsString()
  @MinLength(1)
  @MaxLength(2000)
  question!: string;

  /** Oldest first. The service keeps the last ten turns. */
  @IsOptional()
  @IsArray()
  @ArrayMaxSize(40)
  @ValidateNested({ each: true })
  @Type(() => ChatTurnDto)
  history?: ChatTurnDto[];

  /**
   * What the user is looking at, for example `project PRJ-0042`. Lets "is this
   * on track" resolve without naming the project.
   */
  @IsOptional()
  @IsString()
  @MaxLength(200)
  page_context?: string;
}

export class FeedbackDto {
  @IsInt()
  @Min(-1)
  @Max(1)
  value!: number;
}
