export enum VisitorImageType {
  PROFILE = 'PROFILE',
  FACE_REFERENCE = 'FACE_REFERENCE',
  AADHAAR_FRONT = 'AADHAAR_FRONT',
  AADHAAR_BACK = 'AADHAAR_BACK',
  VISIT_CAPTURE = 'VISIT_CAPTURE',
  OTHER = 'OTHER',
}

